version: "1.0.{build}"
image: Visual Studio 2022

stack: node 18

install:
  - choco install nodejs

branches:
  only:
    - main
cache:
  - node_modules

test_script:
  - npm test

deploy_script:
  - git config --global user.email ""
  - git config --global user.name "marilova19052003"
  - git checkout -b gh-pages
  - rm -rf *
  - cp -r dist/. .
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_PAGES_URL}" gh-pages:gh-pages

environment:
  GH_TOKEN:
    secure: ZwBoAHAAXwBDAG4AdwBYAG8AMgA4ADkARABFAHEAUABDAFAASwBBADgAWABhAFMAQgBHADgAbABIADcAUQBKADgAeAA0ADQAdQBPADkASgA=
  GH_PAGES_URL: github.com/marilova19052003/new---3
